export const CardModul = [
  {
    id: "token-1",
    image: "coins/ethImage.png",
    icon: "coins/ethIcon.png",
    name: "Ethereum (ETH)",
    linkFace: "https://www.fiverr.com/users/madilyani",
    linkTwit: "https://www.fiverr.com/users/madilyani",
    linkLinked: "https://www.fiverr.com/users/madilyani",
    linkTelega: "https://www.fiverr.com/users/madilyani",
    value: "100,000",
    type: "Whitepaper",
    web: "madilyani.com",
    sale: "https://www.fiverr.com/users/madilyani",
  },
  {
    id: "token-2",
    image: "coins/maticImage.png",
    icon: "coins/maticIcon.png",
    name: "EPolygon (MATIC)",
    linkFace: "https://www.fiverr.com/users/madilyani",
    linkTwit: "https://www.fiverr.com/users/madilyani",
    linkLinked: "https://www.fiverr.com/users/madilyani",
    linkTelega: "https://www.fiverr.com/users/madilyani",
    value: "100,000",
    type: "Whitepaper",
    web: "madilyani.com",
    sale: "https://www.fiverr.com/users/madilyani",
  },
  {
    id: "token-3",
    image: "coins/bnbImage.png",
    icon: "coins/bnbIcon.png",
    name: "Binance (BNB)",
    linkFace: "https://www.fiverr.com/users/madilyani",
    linkTwit: "https://www.fiverr.com/users/madilyani",
    linkLinked: "https://www.fiverr.com/users/madilyani",
    linkTelega: "https://www.fiverr.com/users/madilyani",
    value: "100,000",
    type: "Whitepaper",
    web: "madilyani.com",
    sale: "https://www.fiverr.com/users/madilyani",
  },
  {
    id: "token-4",
    image: "coins/ftmImage.png",
    icon: "coins/ftmIcon.png",
    name: "Fantom (FTM)",
    linkFace: "https://www.fiverr.com/users/madilyani",
    linkTwit: "https://www.fiverr.com/users/madilyani",
    linkLinked: "https://www.fiverr.com/users/madilyani",
    linkTelega: "https://www.fiverr.com/users/madilyani",
    value: "100,000",
    type: "Whitepaper",
    web: "madilyani.com",
    sale: "https://www.fiverr.com/users/madilyani",
  },
  {
    id: "token-5",
    image: "coins/avaxImage.png",
    icon: "coins/avaxIcon.png",
    name: "Avalanche (AVAX)",
    linkFace: "https://www.fiverr.com/users/madilyani",
    linkTwit: "https://www.fiverr.com/users/madilyani",
    linkLinked: "https://www.fiverr.com/users/madilyani",
    linkTelega: "https://www.fiverr.com/users/madilyani",
    value: "100,000",
    type: "Whitepaper",
    web: "madilyani.com",
    sale: "https://www.fiverr.com/users/madilyani",
  },
  {
    id: "token-6",
    image: "coins/dotImage.png",
    icon: "coins/dotIcon.png",
    name: "Polkadot (DOT)",
    linkFace: "https://www.fiverr.com/users/madilyani",
    linkTwit: "https://www.fiverr.com/users/madilyani",
    linkLinked: "https://www.fiverr.com/users/madilyani",
    linkTelega: "https://www.fiverr.com/users/madilyani",
    value: "100,000",
    type: "Whitepaper",
    web: "madilyani.com",
    sale: "https://www.fiverr.com/users/madilyani",
  },
];
